# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accordion1_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('image', models.FileField(null=True, upload_to=b'')),
                ('acc1_title', models.CharField(max_length=100)),
                ('acc1_desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='bootstrap_Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_alt', models.CharField(max_length=30)),
                ('slider_title', models.CharField(max_length=30)),
                ('slider_caption', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to=b'')),
                ('slider_fading_type', models.CharField(max_length=100, null=True)),
                ('data_slide_to', models.IntegerField(null=True)),
                ('indicator_name', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='owl_PhotoSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_alt', models.CharField(max_length=30)),
                ('image', models.FileField(blank=True, null=True, upload_to=b'')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
