# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accordion2_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('image', models.FileField(null=True, upload_to=b'')),
                ('acc2_title', models.CharField(max_length=100)),
                ('acc2_desc', models.CharField(max_length=300)),
                ('acc2_content_link', models.URLField(max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='accordion3_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('acc3_title', models.CharField(max_length=100)),
                ('acc3_desc', models.CharField(max_length=400)),
                ('acc3_content_link', models.URLField(max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='accordion4_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('acc4_title', models.CharField(max_length=100)),
                ('acc4_desc', models.CharField(max_length=400)),
                ('acc4_content_link', models.URLField(max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='accordion1_content',
            name='acc1_content_link',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='accordion1_content',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
